### ISSUE TITLE
Laravel 6+ support

### ISSUE THREAD

**Issue by Dronax** [spatie/laravel-translation-loader#101]
Please

**Comment by freekmurze** [comment]
Laravel 6 is supported.

**Comment by Dronax** [comment]
@freekmurze I get error on install:

 Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at /Users/Dronax/code/larafox/vendor/spatie/laravel-translation-loader/src/TranslationServiceProvider.php:51
    47|     {
    48|         $this->app->singleton('translation.loader', function ($app) {
    49|             $class = config('translation-loader.translation_manager');
    50| 
  > 51|             return new $class($app['files'], $app['path.lang']);
    52|         });
    53|     }
    54| }
