### ISSUE TITLE
JSON translation

### ISSUE THREAD

**Issue by thewebartisan7** [spatie/laravel-translation-loader#102]
If we are using JSON file translation, then the "key" can be too short since is a string of max 255. Also this issue seem not merged: https://github.com/spatie/laravel-translation-loader/pull/98

I am using a mix of JSON and groupped translation using PHP array.

What do you think?

**Comment by AlexVanderbist** [comment]
Hi!

>If we are using JSON file translation, then the "key" can be too short since is a string of max 255.
Feel free to change the migration in your own project, or even send a PR that changes the migration in this package. 

>Also this issue seem not merged: #98
Do you still need this? If so, feel free to open a PR with the same code, add me for review and I'll merge it in :) 

Good luck!

**Comment by jorenvh** [comment]
@AlexVanderbist are you still accepting a PR that fixes this issue? I encountered the same and I can confirm that the fix in PR #98 works.

**Comment by freekmurze** [comment]
@jorenvh can you resubmit the fix PRed by #98? We can't merge it anymore as the fork was deleted.
