### ISSUE TITLE
Translate query result

### ISSUE THREAD

**Issue by ext-rgonzalez** [spatie/laravel-translation-loader#104]
hi

Thx for this package, is awesome, am working in a multilanguage app, and i need get the result of query but with your respective translation

any idea ?

some like this 

`return $this->model
                ->select($select)
                ->with($with)
                ->where('id',$id)
                ->get()->**translate**;`

thx

**Comment by AlexVanderbist** [comment]
Hi, you're looking for https://github.com/spatie/laravel-translatable !
