### ISSUE TITLE
How to update a translation line with a JSON formatted value

### ISSUE THREAD

**Issue by hsluis** [spatie/laravel-translation-loader#107]
I'm trying to update an existing translation line by adding an English translation. However this value is an array, and needs to be stored as JSON.

The following code produces an invalid JSON column value:

    $between = [
        'numeric' => 'The :attribute must be between :min and :max.',
        'file'    => 'The :attribute must be between :min and :max kilobytes.',
        'string'  => 'The :attribute must be between :min and :max characters.',
        'array'   => 'The :attribute must have between :min and :max items.',
    ];
    $languageLine = LanguageLine::where('group', 'validation')->where('key', 'between')->first();
    $languageLine->setTranslation('en', json_encode($between));
    $languageLine->save();

**Column value after saving: (see invalid backslashes)**
{"nl":{"numeric":":attribute moet tussen :min en :max zijn.","file":":attribute moet tussen :min en :max kilobytes zijn.","string":":attribute moet tussen :min en :max karakters zijn.","array":":attribute moet tussen :min en :max items bevatten."},"en":"{\\"numeric\\":\\"The :attribute must be between :min and :max.\\",\\"file\\":\\"The :attribute must be between :min and :max kilobytes.\\",\\"string\\":\\"The :attribute must be between :min and :max characters.\\",\\"array\\":\\"The :attribute must have between :min and :max items.\\"}"}

**Comment by weeradach** [comment]
yeah same issue
