### ISSUE TITLE
Cache is always loading the previous strings

### ISSUE THREAD

**Issue by RidaNoor** [spatie/laravel-translation-loader#109]
Hi , 
I wanted to talk more about the issue but it was closed immediately!

public static function getTranslationsForGroup(string $locale, string $group): array
    {
        return Cache::rememberForever(static::getCacheKey($group, $locale), function () use ($group, $locale) {
            return static::query()
                ->where('group', $group)
                ->get()
                ->reduce(function ($lines, self $languageLine) use ($locale) {
                    $translation = $languageLine->getTranslation($locale);
                    if ($translation !== null) {
                        Arr::set($lines, $languageLine->key, $translation);
                    }

                    return $lines;
                }) ?? [];
        });
    }

Here is the function in the model of LanguageLine, and I think here we are setting it to remember cache forever. and then what happens is that it always fetches the old strings

**Comment by freekmurze** [comment]
In response to your latest comment on the previous issue, I've reopened that previous issue (#108). Let's continue the conversation there.
