### ISSUE TITLE
Can't publish migration file

### ISSUE THREAD

**Issue by alexaf2000** [spatie/laravel-translation-loader#128]
Hi! I have been found an error with the library.

After do the "composer require ...", the next thing you want to do is publish the migration file to have the new table required by the library, but which is the issue here? The issue is that if you try to execute ANY "php artisan" command, the Laravel Translation Loader service checks and find that the project doesn't have the desired table. But if artisan commands doesn't work you simply can't publish the migration file and execute-it.

This is the error that is returned with every aritsan command and even the publish command:
```
❯ php artisan vendor:publish --provider="Spatie\TranslationLoader\TranslationServiceProvider" --tag="migrations"


   Illuminate\Database\QueryException 

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.language_lines' doesn't exist (SQL: select * from `language_lines` where `group` = *)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

  • A table was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`. 
    https://laravel.com/docs/master/migrations#running-migrations

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider))

      +25 vendor frames 
  27  routes/web.php:169
      Illuminate\Support\Facades\Facade::__callStatic("transRoute")
```

**Comment by Bogdan-Vieriu** [comment]
Hi, I have a similar error in laravel 8.
After i run :
```bash
composer require spatie/laravel-translation-loader
```
It shows me the same error :
```bash
...
Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.language_lines' doesn't exist (SQL: select * from `language_lines` where `group` = *)
...
```
To fix it i had to remove manually from composer.json the this pakage and deleting composer.lock.
After that i copyed the migration from this repository, I run the migrate comand and after all of this I done composer require ...

A way to fix it is to do in the composer.json of the package the migration ,if is not done yet, and after that contine.
