### ISSUE TITLE
fileLoader-ception

### ISSUE THREAD

**Issue by Arnaudvz** [spatie/laravel-translation-loader#13]
I've experienced Serviceprovider namespaced-translations problem.

```
ServiceProvider::loadTranslationsFrom($path, $namespace)
    {
        $this->app['translator']->addNamespace($namespace, $path);
    }
```

This will add the namespace-hint in the TranslationLoaderManager. But in the function load() this is what happends:

```
 public function load($locale, $group, $namespace = null): array
    {
        $fileTranslations = $this->fileLoader->load($locale, $group, $namespace);
```

$this->fileLoader does not know the namespace-hint that was added by the serviceprovider. Because it's the fileLoader in a fileLoader (fileLoader-ception :) )

Maybe instead of $this->fileLoader->load() you could use parent::load()?

**Comment by sebastiandedeyne** [comment]
Is this still an issue? Gonna close due to inactivity. Feel free to reopen if necessary!

**Comment by markjn** [comment]
Hi, this is a problem for me as well. Is there a workaround?
