### ISSUE TITLE
what differences with hpolthof/laravel-translations-db

### ISSUE THREAD

**Issue by Cyrille37** [spatie/laravel-translation-loader#15]
Hi,
There's already the nice working [hpolthof/laravel-translations-db](https://github.com/hpolthof/laravel-translations-db) so I'm curious to know why another package and do not contribute to the existing one ? My question is motived by that is very difficult to choice what to use, what to contribute when several packages cover same functionalities.
Regards
Cyrille.

**Comment by freekmurze** [comment]
Hi,

I get that picking the right package can sometimes be hard. Some packages do offer the same core functionalities. But if you look more closely there will always be some subtle differences.

The `laravel-translations-db` currently can store translations in the database, comes with a crud-interface and can perform translations via Google Translate

`laravel-translation-loader` offers a driver based way to store and retrieve translations and ships with a default driver that stores translations in the db.

I suggest you take a closer look at the readme's of both packages (and maybe look at some code as well) and then pick the one that feels like the best one for you.
