### ISSUE TITLE
Publishing vendor files throwing errors

### ISSUE THREAD

**Issue by krisnicolaou** [spatie/laravel-translation-loader#21]
I followed the instructions in the `README.md`. When I got to the step where you publish the vendor files I am getting a database error. When running the following command: 
```
php artisan vendor:publish --provider="Spatie\TranslationLoader\TranslationServiceProvider" --tag="migrations"
```

I get the following errors:
```
[Illuminate\Database\QueryException]                                                                                                                                       
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing_v1.language_lines' doesn't exist (SQL: select * from `language_lines` where `group` = routes)
```
```
[PDOException]                                                                                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing_v1.language_lines' doesn't exist
```

I also tried running only the config, but I get the same errors as above:
```
php artisan vendor:publish --provider="Spatie\TranslationLoader\TranslationServiceProvider" --tag="config"
```

Let me know if you need any more information.

**Comment by AlexVanderbist** [comment]
I cannot seem to replicate this issue. What version of Laravel are you using? 

Could you try to install the package on a clean Laravel install to see if the issue persists?

**Comment by krisnicolaou** [comment]
Tested with a fresh installation of Laravel and it works. Must be something with my project that is causing the issue. Thank you for the quick response.

**Comment by dembal1990** [comment]
**+ 1** 
I start with a new project.  
I have a service provider (extend plugin) witch is use trans function, but the table is not exist. 

When I start `$  php artisan migrate` I have a same error.
My workaround: 
```php
<?php

namespace App\TranslationLoader;

use Spatie\TranslationLoader\TranslationLoaders\Db as BaseDb;

class Db extends BaseDb
{
    public function loadTranslations(string $locale, string $group): array
    {
        //Workaround for migration from zero
        try {
            return parent::loadTranslations($locale, $group);
        } catch (\Exception $e) {
            return [];
        }
    }
}
```
