### ISSUE TITLE
Nested Attributes for Laravel Validation

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-translation-loader#24]
I am currently trying to store the `attributes` array of my `validation.php` inside the database with this package but it doesn't seem to work as I see `email` instead of `E-Mail Address` when the error message is displayed from the Laravel Validator.

```
{
    "group": "validation",
    "key": "attributes.email",
    "text": {
        "en": "E-Mail Address",
        "de": "E-Mail Adresse"
    }
}
```

Is it there any way with this package to store nested arrays like the `attributes` one from the `validation.php` inside the database and have it still working?

**Comment by freekmurze** [comment]
Currently this package doesn't support that behaviour.
