### ISSUE TITLE
Export language files to database with command

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-translation-loader#26]
Would be a cool feature if you can import all language files automatically from out your original language files to your database.

**Comment by freekmurze** [comment]
Would be cool, but out of scope for this package.

**Comment by Taronyuu** [comment]
I'm not entirely sure why this is out of scope for this package? Doesn't it make it easier to move away from the regular translation files and start using this package? 

Are you open for a pull request to implement this? Shouldn't take more than a single Artisan command. Unless I'm misunderstanding either you or Cannonb4ll.
