### ISSUE TITLE
PHP compatibility problem

### ISSUE THREAD

**Issue by ablunier** [spatie/laravel-translation-loader#27]
Your package solves a common problem with Laravel localization, but it's only compatible PHP 7 and I think that, as a Laravel dependent package, it should have the same PHP version support.

**Comment by freekmurze** [comment]
To me PHP 5 is dead. I'm not willing to invest time in it anymore. You're of course free to fork the package.

**Comment by ablunier** [comment]
I would like to say the same as you, but I have some long term projects developed in PHP 5.6 to which I need to give support and maintain for a while. Thank you anyway!
