### ISSUE TITLE
Reopening FileLoader can't access namespace "Hints"

### ISSUE THREAD

**Issue by markjn** [spatie/laravel-translation-loader#28]
>  Arnaudvz commented on Oct 28, 2016
> I've experienced Serviceprovider namespaced-translations problem.
> 
> ServiceProvider::loadTranslationsFrom($path, $namespace)
>     {
>         $this->app['translator']->addNamespace($namespace, $path);
>     }
> This will add the namespace-hint in the TranslationLoaderManager. But in the function load() this is what happends:
> 
>  public function load($locale, $group, $namespace = null): array
>     {
>         $fileTranslations = $this->fileLoader->load($locale, $group, $namespace);
> $this->fileLoader does not know the namespace-hint that was added by the serviceprovider. Because it's the fileLoader in a fileLoader (fileLoader-ception :) )
> 
> Maybe instead of $this->fileLoader->load() you could use parent::load()?
> 
> Using the translation loader with third party integrations that have their own language files does not work. 

To add to what Arnaudvz said, 

If it doesn't know the namespace, it won't load any third party language files from packages.

It's fixable by assigning the $path and $files properties of the fileLoader to the TranslationLoaderManager in the construct method. Then, instead of getting fileTranslations from the FileLoader that was passed in, you can use parent::load.

**Comment by freekmurze** [comment]
I don't 100% understand what the problem is. 

If it's an easy fix, could you submit a non-breaking well tested PR?

**Comment by markjn** [comment]
Hi Freek,

I've never worked on an open-source project before. I'm self taught and
have only been doing this a couple years. If you think I can contribute,
then yes, I'll happily put in the work. I'm grateful for the opportunity.
The fix I have is easy and functional, and I am 99% sure it doesn't break
anything else. It is being tested all the time in the site I built for my
company. I can break down the problem and my proposed solution in way more
detail if you'd like.

Thanks,
Mark

**Comment by freekmurze** [comment]
Because this package is a bit low priority for me I'm not going to invest a lot of time in it myself.

Send me the best PR you can manage and we'll see from there on.
