### ISSUE TITLE
Editing vendor translation

### ISSUE THREAD

**Issue by esseremmerik** [spatie/laravel-translation-loader#31]
All edited lines are saved with their group and key. Is it possible to edit lines from vendor packages and how do I save them in the database?

**Comment by freekmurze** [comment]
No, that is currently not supported. 

I'd accept a PR that adds this to the package.

**Comment by uyab** [comment]
@freekmurze I'm thinking about adding new column for namespace, with default to `*`, what do you think about that? I'll try to create a PR if it is ok.

**Comment by freekmurze** [comment]
Send a PR with tests and I'll have look.

**Comment by robov** [comment]
Would be awesome to override vendor packages in the database
