### ISSUE TITLE
$locale is null

### ISSUE THREAD

**Issue by MrStaun** [spatie/laravel-translation-loader#39]
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Spatie\TranslationLoader\TranslationLoaderManager::getTranslationsForTranslationLoaders() must be of the type string, null given, called in /Users/markstaun/Dropbox/Laravel/webshop/vendor/spatie/larav
  el-translation-loader/src/TranslationLoaderManager.php on line 27`

The package works fine and i can access my web application, but when i try to do something in the termnial i get this error.

When i edit the following everything works perfectly fine.
TranslationLoaderManager:
`$loaderTranslations = $this->getTranslationsForTranslationLoaders($locale, $group, $namespace);`
to:
`$loaderTranslations = $this->getTranslationsForTranslationLoaders($locale ?? '', $group, $namespace);`

I'm currently using Laravel 5.4 - Is there anything i'm doing wrong?

**Comment by freekmurze** [comment]
Strange that we ourselves haven't come across this problem yet. Could you PR this to the package?

**Comment by MrStaun** [comment]
Sorry, I don't know how to work with PR's.

I'm just a junior dev and I don't know WHY the package in didn't work right
away in my project. The only thing I know is that changing that one line
fixed it.

(screenshot attached)


Bests,
Mark

2017-08-05 12:45 GMT+04:00 Freek Van der Herten <notifications@github.com>:
