### ISSUE TITLE
Enable usage in Javascript

### ISSUE THREAD

**Issue by pkid169** [spatie/laravel-translation-loader#47]
Hey there! This is probably not part of this project, but it'll be great if you guys can create another package for front-end. Something like https://github.com/rmariuzzo/laravel-js-localization, but using the same DB as source as this project.

You guys've created some awesome stuffs by the way. I'll send you a postcard one day!

**Comment by freekmurze** [comment]
Thanks!

I think you've just got yourself an open source project of your own 😄
