### ISSUE TITLE
UTF-8 encoding problem with special german characters

### ISSUE THREAD

**Issue by akogler37** [spatie/laravel-translation-loader#50]
Hey, 

I'm not sure if this is related to my setup or a general problem. If I do e. g.: 

```
use Illuminate\Database\Seeder;
use Spatie\TranslationLoader\LanguageLine;

class LanguageLinesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        LanguageLine::create([
            'group' => 'validation',
            'key' => 'required',
            'text' => ['en' => 'The :attribute field is required.', 'de' => "Das Feld :attribute muss ausgefüllt sein."],
        ]);
    }
}
```

I get the entry `{"en":"The :attribute field is required.","de":"Das Feld :attribute muss ausgef\u00fcllt sein."}` in the MySQL database. I was hoping to get `ausgefüllt` instead of `ausgef\u00fcllt`.

**Comment by freekmurze** [comment]
I'm thinking this problem is not caused by this package, but by your database configuration.

**Comment by akogler37** [comment]
@freekmurze I guess my problem report isn't really a problem, it's just the way it used to work as I didn't experience any problems after testing the package for a while. Many thanks for the quick follow-up.
