### ISSUE TITLE
Fallback does not work

### ISSUE THREAD

**Issue by skoTner** [spatie/laravel-translation-loader#51]
If using database only for translation and no files, the fallback functionality of Laravel does not work.

Eg:
```
Group: validation
Key: required
Text: {"en":"This is a required field","nl":"Dit is een verplicht veld"}
```

When using `trans('validation.required');` and **app.locale** is set to **en** or **nl**, all works fine. But when changing locale to another language the text becomes blank. It should fallback to **en** in this case.

**Comment by freekmurze** [comment]
Could your PR a failing test and a fix?

**Comment by freekmurze** [comment]
Fixed!
