### ISSUE TITLE
 string of translations into an array?

### ISSUE THREAD

**Issue by LusenkoSasha** [spatie/laravel-translation-loader#55]
How can I pull all the translations out of the table and that they are in an array, not a string?

**Comment by freekmurze** [comment]
Could you give us a code snippet that you'd wish would work?

**Comment by skalero01** [comment]
I imagine that LusenkoSasha refers for example in validation.attributes

```
attributes' => [
        'title' => 'Titulo',
        'name'  => 'Nombre',
        'url'   => 'URL',
        'value' => 'Valor'
]
```

I have the same question, how could i store the attributes value?

**Comment by skalero01** [comment]
I found the answer to using arrays on the package

I case of the `validation.attributes` you just need to add a new row on LanguageLine

```
LanguageLine::create([
      'group' => 'validation',
     'key' => 'attributes.title',
     'text' => ['es' => 'Titulo']
]);
```
And that with every element
