### ISSUE TITLE
updating translation of strings for multiple languages.

### ISSUE THREAD

**Issue by Naveedali1234** [spatie/laravel-translation-loader#57]
hello !!
i really appreciate the work of spatie. But i noticed that there is no clue for updating the existing strings in multiple languages. How we can achieve this suppose if we have a CMS system in which an admin can update the text of his website through CMS by fetching the old strings which are in multiple languages and then update all of them according to his needs. if this can be done through this package then it would be the plus point.

give me apologies if i am wrong.

Kind regards

**Comment by freekmurze** [comment]
Providing a UI for this is out of scope for this package.

**Comment by Naveedali1234** [comment]
i am having problem in downloading the package through composer. :(
