### ISSUE TITLE
support with laravel previous version 5.4.* and php 5.6

### ISSUE THREAD

**Issue by amirgee007** [spatie/laravel-translation-loader#58]
"php": "=5.6",
"laravel/framework": "5.4.*",

How can i use this package for these settings.

i have tried this composer require spatie/laravel-translation-loader

but it said you need php 7.1 etc

**Comment by freekmurze** [comment]
We don't support those old versions anymore.

If you need support for L5.4 or PHP 5.6 invest your time by forking our code and maintaining your own version.
