### ISSUE TITLE
An error when installing

### ISSUE THREAD

**Issue by skalero01** [spatie/laravel-translation-loader#60]
Hi, just for informing you that there is an error when a new user is trying to install the package.

After installing via composer the next error is gotten

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string 
at vendor\spatie\laravel-translation-loader\src\TranslationServiceProvider.php: 50
  46:     {
  47:         $this->app->singleton('translation.loader', function ($app) {
  48:             $class = config('translation-loader.translation_manager');
  49:
  50:             return new $class($app['files'], $app['path.lang']);
  51:         });
  52:     }
  53: }
  54:
``` 

To get it functional i had to create a new file in config/translation-loader and add your example configuration and with that it started working

Regards

**Comment by freekmurze** [comment]
I can't reproduce this error.

**Comment by VasiliDarozhkin** [comment]
Just got it after installing
When a blade fail contains `__('SomeString')`, $class variable in vendor/spatie/laravel-translation-loader/src/TranslationServiceProvider.php in registerLoader method is NULL.

So I had to execute `php artisan config:clear`, after which it works
