### ISSUE TITLE
Language Line model has problems with traits

### ISSUE THREAD

**Issue by skalero01** [spatie/laravel-translation-loader#61]
Hi, just to comment that the Language File model has a problem working with another packages that uses traits, like the `soft deletes` function. I found the error, in the `LanguageLine.php` its needed to add a `parent::boot()`

```
public static function boot()
    {
        parent::boot();
        static::saved(function (LanguageLine $languageLine) {
            $languageLine->flushGroupCache();
        });

        static::deleted(function (LanguageLine $languageLine) {
            $languageLine->flushGroupCache();
        });
    }
```

I will appreciate a lot to fix this problem

Regards!

BTW just for not opening another issue, the `getTranslation` function have an error because it doesnt validate if the key exists on the array, so i solved it using this function 

```
public function getTranslation(string $locale): string
    {
        if(isset($this->text[$locale]))
            return $this->text[$locale];
        if(isset($this->text[config('app.fallback_locale')]))
            return $this->text[config('app.fallback_locale')];
        return '';
    }
```

**Comment by freekmurze** [comment]
Feel free to send separate PRs to fix both problems.
