### ISSUE TITLE
Translation Strings As Keys

### ISSUE THREAD

**Issue by pmayet** [spatie/laravel-translation-loader#73]
Hi,

Thank's for this work.
Is it possible tu use with translation strings as keys ?

Best regards,

**Comment by freekmurze** [comment]
I don't understand the question. Could you give an example of what you are trying to achieve?

**Comment by myriamornecipe** [comment]
Hi,

I think he's talking about that :

https://laravel.com/docs/5.6/localization#replacing-parameters-in-translation-strings

Isn't it ?

Regards,

**Comment by freekmurze** [comment]
I think it supports that already, if not I'm open for a PR that adds this.
