### ISSUE TITLE
Some keys are not translated

### ISSUE THREAD

**Issue by Uweb95** [spatie/laravel-translation-loader#76]
Hello, I have the following problem:
If I translated the variables via "{{_('group.key')}}", this works fine for some, but records 43-54 are not translated. 
![image](https://user-images.githubusercontent.com/16607172/43679306-7095497e-9823-11e8-8e85-98482fc8701b.png)
![image](https://user-images.githubusercontent.com/16607172/43679330-d68b8554-9823-11e8-85e6-9a64353708dc.png)

PHP: 7.2.8
Laravel: 5.6
No log file availlable
Cache cleared, Server restarted: no changes

**Comment by freekmurze** [comment]
I can't recreate the problem. Could you please PR a failing test?
