### ISSUE TITLE
Subkey i.e. see lang/en/validation.php

### ISSUE THREAD

**Issue by angryalf** [spatie/laravel-translation-loader#78]
Hi!

Thank you so much for your work!
Also is possible to have keys like sub-array (like inside lang/en/validation.php), i.e.:

**trans('validation.between.numeric')** cause error '**Return value of Spatie\TranslationLoaderss\LanguageLine::getTranslation() must be of the type string or null, array returned**'

See Record in DB for this:

`id | group | key | text | created_at | updated_at`

`20 | validation | between.numeric | {"en":"The :attribute must be between :min and :ma... | 2018-08-24 07:19:13 | 2018-08-24 07:19:13`

Regards!

**Comment by freekmurze** [comment]
I don't think this is possible now, but if it's simple to support this, I'd accept a PR with tests and an updated readme that adds this to the package.
