### ISSUE TITLE
installation on existiong Laravel project returns error

### ISSUE THREAD

**Issue by alewolf** [spatie/laravel-translation-loader#80]
Hi

When installing the package on an existing Laravel project on which I've developed for some time already (db and several tables already exist), the installation routine returns an error. 

<img width="370" alt="download" src="https://user-images.githubusercontent.com/7146794/44837308-8fc58500-ac39-11e8-9aee-4e7a3ae9e945.png">

Am I doing something wrong here, or is this an error in the installation routine?

On a naked Laravel basic installation the installer works fine. If the intaller is only meant to work while setting up an completely new Laravel project, then I wonder how the package needs to be installed on an existing project. Could you point out the steps that need to be done in order to get it to work on an existing project? Or even better, could you update the installer to make it work on existing projects?

**Comment by freekmurze** [comment]
Probably there is something running from our package before the migration is run. I'd accept a PR that fixes this.

**Comment by NioTeX** [comment]
Any updates here?
@alewolf did you find a solution by any chance?

**Comment by alewolf** [comment]
Not a really nice one. Create the database tables manually and then it sould work.

**Comment by NioTeX** [comment]
I actually did that locally, and works well, but the problem is my CI solution also needs to install the package, and that environment doesn't even have a Database available to it.
I'll probably try to pinpoint the exact thing that tries to use it.

**Comment by alewolf** [comment]
I submitted a pull request that solves this in a not ideal way. Aa db call is being made on each run to check a condition, but it works. If you choose to implement this as a custom override it will not be upgrade safe. Once the original package gets updated, and the custom code overwritten, the issue reappears, unless the database table exist. 

Have a look at my pull request here: https://github.com/spatie/laravel-translation-loader/pull/83/commits/f65cbb5d0caa76a7e35e593c34a5b2a044c17b90

**Comment by NioTeX** [comment]
Omg, thanks for that! Much appreciated :D
