### ISSUE TITLE
Attributes Names

### ISSUE THREAD

**Issue by soyjonathanespinosa** [spatie/laravel-translation-loader#87]
Hello,

How can I use the lang file in the section of attibutes custom, because is not working.

Thank you

**Comment by freekmurze** [comment]
There's too little here to help you with this problem. If you spot an error in our package, please submit a failing test for us to fix.

**Comment by keevitaja** [comment]
@soyjonathanespinosa was probably talking about adding attribute name translations.

![image](https://user-images.githubusercontent.com/158787/105990505-3c2a2080-60ab-11eb-82ac-8e40c9fbd88a.png)

https://github.com/laravel/laravel/blob/8.x/resources/lang/en/validation.php#L141

i'm wondering the same thing
