### ISSUE TITLE
Add Laravel 5.8 support, please

### ISSUE THREAD

**Issue by ultimateBusiness** [spatie/laravel-translation-loader#91]

**Comment by freekmurze** [comment]
Done.

**Comment by elijahworkz** [comment]
Now it cannot be installed on Laravel 5.7
`Problem 1
    - Installation request for spatie/laravel-translation-loader ^2.3 -> satisfiable by spatie/laravel-translation-loader[2.3.0].
    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - spatie/laravel-translation-loader 2.3.0 requires illuminate/translation ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/translation[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - don't install illuminate/translation 5.8.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/translation v5.8.0|don't install laravel/framework v5.7.28
    - don't install illuminate/translation v5.8.2|don't install laravel/framework v5.7.28
    - don't install illuminate/translation v5.8.3|don't install laravel/framework v5.7.28
    - don't install illuminate/translation v5.8.4|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].`

I wanted to upgrade to 5.8 but then your [laravel-server-side-rendering](https://github.com/spatie/laravel-server-side-rendering) package is not working as there is not 5.8 support yet
