### ISSUE TITLE
In memory dynamic translations

### ISSUE THREAD

**Issue by dizco** [spatie/laravel-translation-loader#99]
Hi,

Very nice project! For one of my projects, I didn't need the overhead of database translations, but I wanted to be able to dynamically register translations in the translations loader on application boot. I have developed my own very simple `InMemoryTranslationLoader` for this.

Would you be interested in a PR for this? Or is the repo mainly focused on DB translations?

**Comment by freekmurze** [comment]
If this change is simple and the PR contains tests and an updated readme, I’ll consider merging it.

**Comment by dizco** [comment]
For what its worth... As I started working on this feature, I discovered an easier way to accomplish what I wanted to do. My solution doesn't require laravel-translation-loader.

It's possible to hook directly on the `Translator` instance and use the `addLines` function to dynamically inject some translations.

In my `AppServiceProvider`:
```php
public function boot()
{
    /** @var Translator $translator */
    $translator = $this->app->make('translator');
    
    $translator->load('*', 'routes', 'en'); // Need to do this before dynamically adding lines to a group, otherwise the Translator will think that it has already loaded the whole group.

    $translator->addLines(['routes.index' => 'my-route'], 'en);
}
```

While this has severe limitations, it fits my needs for now. Hope this helps someone else some day
